package sqlworkbench

import (
	"strings"
	"testing"
)

func TestQuoteIdentifier(t *testing.T) {
	if got, want := QuoteIdentifier(`odd"name`), `"odd""name"`; got != want {
		t.Fatalf("QuoteIdentifier() = %q, want %q", got, want)
	}
}

func TestQuoteLiteral(t *testing.T) {
	if got, want := QuoteLiteral("team's"), `'team''s'`; got != want {
		t.Fatalf("QuoteLiteral() = %q, want %q", got, want)
	}
}

func TestGeneratedTableDefinition(t *testing.T) {
	detail := ObjectDetail{
		Object:      DatabaseObject{Schema: "public", Name: "orders", Kind: ObjectTable},
		Columns:     []ObjectColumn{{Name: "id", DataType: "bigint", Nullable: false, Identity: "BY DEFAULT"}, {Name: "note", DataType: "text", Nullable: true}},
		Constraints: []NamedDefinition{{Name: "orders_pkey", Definition: "PRIMARY KEY (id)"}},
	}
	definition := generatedTableDefinition(detail)
	for _, expected := range []string{`CREATE TABLE "public"."orders"`, `"id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL`, `CONSTRAINT "orders_pkey" PRIMARY KEY (id)`} {
		if !strings.Contains(definition, expected) {
			t.Fatalf("definition missing %q:\n%s", expected, definition)
		}
	}
}

func TestDatabaseObjectDisplayName(t *testing.T) {
	object := DatabaseObject{Name: "lookup", Kind: ObjectFunction, IdentityArguments: "text, integer"}
	if got, want := object.DisplayName(), "lookup(text, integer)"; got != want {
		t.Fatalf("DisplayName() = %q, want %q", got, want)
	}
}

func TestObjectColumnNames(t *testing.T) {
	object := DatabaseObject{Schema: "billing", Name: "order items", Kind: ObjectTable}
	column := ObjectColumn{Name: "order id", DataType: "uuid", Nullable: false}
	if got, want := column.DisplayName(), "order id  uuid, not null"; got != want {
		t.Fatalf("DisplayName() = %q, want %q", got, want)
	}
	if got, want := column.SQLName(), `"order id"`; got != want {
		t.Fatalf("SQLName() = %q, want %q", got, want)
	}
	if got, want := column.QualifiedName(object), `"billing"."order items"."order id"`; got != want {
		t.Fatalf("QualifiedName() = %q, want %q", got, want)
	}
}

func TestObjectKindHasColumns(t *testing.T) {
	for _, kind := range []ObjectKind{ObjectTable, ObjectView, ObjectMaterializedView} {
		if !ObjectKindHasColumns(kind) {
			t.Errorf("ObjectKindHasColumns(%q) = false", kind)
		}
	}
	for _, kind := range []ObjectKind{ObjectSequence, ObjectFunction} {
		if ObjectKindHasColumns(kind) {
			t.Errorf("ObjectKindHasColumns(%q) = true", kind)
		}
	}
}
